---
title: "Class 2"
author: "Joshua Carpenter"
date: "12 Sep 2023"
format: pdf
---

```{r setup, results='hide', message=FALSE}
library(tidyverse)
```


This code is borrowed from the last lecture; it creates a tibble for plotting.

```{r}
plotdf = tibble(
	x = rnorm(1000, sd = 0.5),
	y = 1 + 2 * x + rnorm(1000)
)
```

Next up, a histogram.

```{r, message=FALSE}
ggplot(plotdf, aes(x = x)) +
    geom_histogram()
```

```{r chunkname, message=F}
mytibble = tibble(
  norm = rnorm(500, mean = 1),
  log = norm > 0,
  abs = abs(norm)
)
ggplot(mytibble, aes(x = abs)) +
  geom_histogram()
```

The median value of the above histogram is `r mytibble %>% summarise(median = median(abs))`.

Text formatting 
------------------------------------------------------------

*italic*  or  _italic_

**bold**  or  __bold__

`code`

superscript^2^ and subscript~2~


Headings
------------------------------------------------------------

# 1st Level Header

## 2nd Level Header

### 3rd Level Header


Lists
------------------------------------------------------------

*   Bulleted list item 1

*   Item 2

    * Item 2a

    * Item 2b

1.  Numbered list item 1

1.  Item 2. The numbers are incremented automatically in the output.


Tables 
------------------------------------------------------------

First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell